import argparse
import subprocess
import os
import shutil

#set up parser
parser = argparse.ArgumentParser(
                    prog='annotator',
                    description='Script that performs the functional annotation using blast+ and interproscan',
                    epilog='')

parser.add_argument('inputdir',help="path to the pipeline directory generated by assembly.py (the one containing a working directory and results directory) (make sure this is an absolute path)")
parser.add_argument('dbdir',help="path to the database folder (for instructions on what this folder should contain use the --dbhelp flag)")
parser.add_argument('--dbhelp', help="instructions on creating the dbdir directory" )
parser.add_argument('-s', '--snail', help="the name of the snail genome being assembled (default = lmaximus)" )
parser.add_argument('-t', '--threads', help="the amount of threads you'd like to use (default = 94)")
parser.add_argument('-sf', '--start_from', help="the step of the assembly to start from, to see the list of steps use -sl")
parser.add_argument('-sl', '--stepslist', action='store_true',help="Showcase a list of steps for the -sf flag")


args=parser.parse_args()


assemblydir=args.inputdir
dbdir=args.dbdir
threads=args.threads
dbh=args.dbhelp
step=args.start_from
sl=args.stepslist
snail=args.snail


prots=f"{assemblydir}/results/{snail}_proteins_filtered.aa"

if os.path.isdir(f"{assemblydir}/working_directory/annotation") == False:
    os.mkdir(f"{assemblydir}/working_directory/annotation")

annodir=f"{assemblydir}/working_directory/annotation"


steplist=["blast","interproscan"]
if sl:
    print("masking (already the start of the pipeline so will not have any meaningful effect)\nbraker")
    quit()

if sl:
    print("masking (already the start of the pipeline so will not have any meaningful effect)\nbraker")
    quit()

if dbh:
    print("First create a top level directory, this directory will contain all your databases.\nThe databases the tool expects are the eggNOG, SWISS-PROT (uniprot) and TrEMBL databases, but adding others or leaving some out shouldn't break it, just follow the same steps.\nNext create a subfolder for each database, called eggnog/ swissprot/ trembl/ kegg/ and interpro/\nDownload each database in FASTA format and place this file in the corresponding folder (make sure they have the .fasta extension not .fa, .aa, etc).\nCD into each directory and run the command makeblastdb -in (fasta file) -dbtype prot.\nNow the database directory is ready, and can be used for the command, the directory you give the command should be the top level directory you made.\n(Make sure to not add any additional files to your db folders)")
    quit()

if threads==None:
    threads=94



if snail == None:
    snail="lmaximus"

snail=args.snail.replace(" ","")

for db in os.listdir(dbdir):
    for dbfile in os.listdir(f"{dbdir}/{db}"):
        if dbfile.endswith(".fasta"):
            iddict={}
            edict={}
            outlines=""
            with open(f"{dbdir}/{db}/{dbfile}","r") as file:
                lines=file.readlines()
                for line in lines:
                    if line.startswith(">"):
                        ids=line.split(" ")[0][1:].strip()
                        iddict[ids]=line

            subprocess.run(f"blastp -outfmt 6 -db {dbdir}/{db}/{dbfile} -query {prots} -num_threads {threads} > {annodir}/{snail}_{db}.tsv",shell=True)
            with open(f"{annodir}/{snail}_{db}.tsv","r") as file:
                lines=file.readlines()
                for line in lines:
                    cols=line.split("\t")
                    idq=cols[0]
                    edict[idq]=0.0001
                for line in lines:
                    cols=line.split("\t")
                    idq=cols[0]
                    e=cols[10]
                    if float(e) <= 0.0001:
                        if float(e) < float(edict[idq]):
                            edict[idq]=e
                for line in lines:
                    cols=line.split("\t")
                    ids=cols[1]
                    idq=cols[0]
                    info=iddict[ids]
                    e=cols[10]
                    if float(e) == float(edict[idq]):
                        outlines+=f"{line.strip()}\t{info[1:]}\n"
            with open(f"{assemblydir}/results/{snail}_{db}_filtered_blastresults.tsv","w") as file:
                file.write(outlines)



