import argparse
import subprocess
import os
import shutil

#set up parser
parser = argparse.ArgumentParser(
                    prog='annotator',
                    description='Script that performs the functional annotation using blast+ and interproscan',
                    epilog='')

parser.add_argument('inputdir',help="path to the pipeline directory generated by assembly.py (the one containing a working directory and results directory)")
parser.add_argument('dbdir',help="path to the database folder (for instructions on what this folder should contain use the --dbhelp flag)")
parser.add_argument('-i', '--interprodir',help="path to the directory containing the interproscan.sh script (default /media/data2/my_interproscan/interproscan-5.74-105.0/")
parser.add_argument('--dbhelp', help="instructions on creating the dbdir directory" )
parser.add_argument('-s', '--snail', help="the name of the snail genome being assembled (default = lmaximus)" )
parser.add_argument('-t', '--threads', help="the amount of threads you'd like to use (default = 94)")
parser.add_argument('-sf', '--start_from', help="the step of the assembly to start from, to see the list of steps use -sl")
parser.add_argument('-sl', '--stepslist', action='store_true',help="Showcase a list of steps for the -sf flag")
parser.add_argument('-f', '--fullanno', help="determine which genes are fully annotated (BLAST result, IPR domains, GO terms) (this flagged script is to be ran after obtaining the results (the outputfile will be a tsv containing a list of all fully annotated genes)")

args=parser.parse_args()


assemblydir=args.inputdir
dbdir=args.dbdir
threads=args.threads
dbh=args.dbhelp
step=args.start_from
sl=args.stepslist
snail=args.snail
ipr=args.interprodir
f=args.fullanno

if os.path.isdir(assemblydir) == False:
    print(f"ERROR: directory: {assemblydir} does not exist, exiting")
    quit()

if f != None:
    fullannoprot={}
    blast=f"{assemblydir}/results/{snail}_{f}_filtered_blastresults.tsv"
    ipr=f"{assemblydir}/results/{snail}_ipr_domains.tsv"
    out=""
    with open(ipr,"r") as file:
        lines=file.readlines()
        for line in lines:
            id=line.split("\t")[0]
            if "GO" in line:
                fullannoprot[id]=False
    with open(blast,"r") as file:
        lines=file.readlines()
        for line in lines:
            id=line.split("\t")[0]
            if id in fullannoprot:
                fullannoprot[id]=True
    for prot in fullannoprot:
        if fullannoprot[prot]:
            out+=f"{prot}\n"
    with open(f"{assemblydir}/results/{snail}_fully_annotated_genes_{f}.tsv","w") as file:
        file.write(out)

    quit()

print("oops")
quit()

if ipr==None:
    ipr="/media/data2/my_interproscan/interproscan-5.74-105.0/"
if os.path.isdir(ipr) == False:
    print(f"ERROR: directory: {ipr} does not exist, exiting")
    quit()


if os.path.isdir(dbdir) == False:
    print(f"ERROR: directory: {dbdir} does not exist, exiting")
    quit()

prots=f"{assemblydir}/results/{snail}_proteins_filtered.aa"

if os.path.isdir(f"{assemblydir}/working_directory/annotation") == False:
    os.mkdir(f"{assemblydir}/working_directory/annotation")

annodir=f"{assemblydir}/working_directory/annotation"


steplist=["blast","interproscan"]
if sl:
    print("blast (already the start of the pipeline so will not have any meaningful effect)\ninterproscan")
    quit()

if step != None and step not in steplist:
    print("ERROR: please input a valid step to start from (to see a list of possible steps use -sl)")
    quit()

if dbh:
    print("First create a top level directory, this directory will contain all your databases.\nThe database the tool expects is SWISS-PROT (uniprot) but adding others or leaving some out shouldn't break it, just follow the same steps.\nNext create a subfolder for each database named after the database.\nDownload each database in FASTA format and place this file in the corresponding folder (make sure they have the .fasta extension not .fa, .aa, etc).\nCD into each directory and run the command makeblastdb -in (fasta file) -dbtype prot.\nNow the database directory is ready, and can be used for the command, the directory you give the command should be the top level directory you made.\n(Make sure to not add any additional files to your db folders)")
    quit()

if threads==None:
    threads=94



if snail == None:
    snail="lmaximus"

snail=args.snail.replace(" ","")

if step != "interproscan":
    for db in os.listdir(dbdir):
        for dbfile in os.listdir(f"{dbdir}/{db}"):
            if dbfile.endswith(".fasta"):
                iddict={}
                edict={}
                outlines=""
                with open(f"{dbdir}/{db}/{dbfile}","r") as file:
                    lines=file.readlines()
                    for line in lines:
                        if line.startswith(">"):
                            ids=line.split(" ")[0][1:].strip()
                            iddict[ids]=line

                subprocess.run(f"blastp -outfmt 6 -db {dbdir}/{db}/{dbfile} -query {prots} -num_threads {threads} > {annodir}/{snail}_{db}.tsv",shell=True)
                with open(f"{annodir}/{snail}_{db}.tsv","r") as file:
                    lines=file.readlines()
                    for line in lines:
                        cols=line.split("\t")
                        idq=cols[0]
                        edict[idq]=0.0001
                    for line in lines:
                        cols=line.split("\t")
                        idq=cols[0]
                        e=cols[10]
                        if float(e) <= 0.0001:
                            if float(e) < float(edict[idq]):
                                edict[idq]=e
                    for line in lines:
                        cols=line.split("\t")
                        ids=cols[1]
                        idq=cols[0]
                        info=iddict[ids]
                        e=cols[10]
                        if float(e) == float(edict[idq]):
                            outlines+=f"{line.strip()}\t{info[1:]}\n"
                with open(f"{assemblydir}/results/{snail}_{db}_filtered_blastresults.tsv","w") as file:
                    file.write(outlines)

subprocess.run(f"{ipr}/interproscan.sh -i {prots} -f tsv -o {assemblydir}/results/{snail}_ipr_domains.tsv  -cpu {threads} --goterms",shell=True)
